title: NMR Training
description: A collection of practical exercises and examples to learn the operation of NMR spectrometers
theme: just-the-docs
repository: waudbygroup/nmr-training # for github-metadata
url: https://waudbygroup.github.io/nmr-training

aux_links:
  View on GitHub: https://github.com/waudbygroup/nmr-training

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

#callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Distributed under a CC-BY-NC licence"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/waudbygroup/nmr-training" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# For copy button on code
enable_copy_code_button: true

# External navigation links
nav_external_links:
  - title: Waudby Lab
    url: https://waudbylab.org
  # - title: NMR Training on GitHub
  #   url: https://github.com/waudbygroup/nmr-training

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.8.0"
