title: NMR training exercises
description: A collection of practical exercises and examples to learn the operation of NMR spectrometers
theme: just-the-docs

url: https://waudbygroup.github.io/nmr-training

aux_links:
  Template Repository: https://github.com/waudbygroup/nmr-training
